name: Bug report
description: Submit a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        **New to Stability Matrix?**
        For help or advice on using Stability Matrix, try one of the following options instead of opening a GitHub issue:
        - Asking on our [Discord server](https://link.lykos.ai/discord?ref=github-issue-template)
        - Creating a post on [Discussions](https://github.com/LykosAI/StabilityMatrix/discussions)
        
        This template is for reporting bugs experienced within the Stability Matrix app. 
        If your issue is regarding Package behavior when running it, or when installing or updating a specific Package, please use the [Package issue template](https://github.com/LykosAI/StabilityMatrix/issues/new/choose) instead.
        
        Make sure to also search the [existing issues](https://github.com/LykosAI/StabilityMatrix/issues) to see if your issue has already been reported.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give a clear and concise description of what happened. Provide screenshots or videos of UI if necessary. Also tell us, what did you expect to happen?
      placeholder: |
        When dragging a model file into the ... page to import, I expected to see...
        
        Instead, I saw...
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Include a minimal step-by-step guide to reproduce the issue if possible.
      placeholder: |
        1. Open Stability Matrix
        2. Go to the ... page
        3. Click on the ... button
        4. Expected to see ... open, but instead ...
  - type: textarea
    id: app-logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output. (This will be automatically formatted, so no need for backticks.)
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Stability Matrix are you running? (Can be found at the bottom of the settings page)
      placeholder: ex. v2.11.0
    validations:
      required: true
  - type: dropdown
    id: os-platform
    attributes:
      label: What Operating System are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
